### ISSUE TITLE
Website Updates

### ISSUE THREAD

**Issue by doms** [BenEmdon/BenEmdon.GitHub.io#7]
Helloooo, kind sir. 👋🏾 

It might be time to update this as you've graduated, and you're doing big things now. ✨

<p align="center">
	<img width=550 src="https://user-images.githubusercontent.com/8808097/100159567-d6c77280-2e62-11eb-9cc6-68b6b1fb0754.png" />
</p>

cc:// @BenEmdon

**Comment by BenEmdon** [comment]
Hahaha sure 😄

**Comment by BenEmdon** [comment]
Updated! Thanks for opening this issue 🖖
